# Generated by Django 3.2.5 on 2022-01-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isBusinessClient',
            field=models.BooleanField(default=False),
        ),
    ]
