# Generated by Django 3.2.5 on 2022-01-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220105_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='tags',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tags',
            field=models.TextField(default='', null=True),
        ),
    ]
