# Generated by Django 3.2.5 on 2022-02-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_hotel_linktobookingpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='bookingRating',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=2, null=True),
        ),
    ]
