# Generated by Django 3.2.5 on 2022-02-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_hotel_bookingrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='starRating',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
