# Generated by Django 3.2.5 on 2022-02-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_hotel_starrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favouriteHotels',
            field=models.ManyToManyField(default=None, to='api.Hotel'),
        ),
    ]
