# Generated by Django 3.2.5 on 2022-02-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_favouritehotels'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='isFetchedFromTripadvisor',
            field=models.BooleanField(default=True),
        ),
    ]
