# Generated by Django 3.2.5 on 2022-02-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_restaurant_isfetchedfromtripadvisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='tripadvisorLink',
            field=models.TextField(default=''),
        ),
    ]
