# Generated by Django 3.2.5 on 2022-02-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_restaurant_tripadvisorlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='destID',
            field=models.CharField(max_length=12),
        ),
    ]
