# Generated by Django 3.2.5 on 2022-02-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_city_destid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='destID',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
