# Generated by Django 3.2.5 on 2022-02-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_city_destid'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='linkToTripadvisorPic',
            field=models.TextField(default='', null=True),
        ),
    ]
