# Generated by Django 3.2.5 on 2022-03-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_restaurant_linktotripadvisorpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favouriteRestaurants',
            field=models.ManyToManyField(default=None, to='api.Restaurant'),
        ),
    ]
