# Generated by Django 3.2.5 on 2022-03-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_searchphrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchphrase',
            name='phrase',
            field=models.TextField(unique=True),
        ),
    ]
