# Generated by Django 3.2.5 on 2022-03-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_searchphrase_phrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchphrase',
            name='phrase',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
    ]
