# Generated by Django 3.2.5 on 2022-03-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_cachedlisthotels'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedlisthotels',
            name='cached_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='cachedlisthotels',
            unique_together={('city', 'keywordHash')},
        ),
    ]
