# Generated by Django 3.2.5 on 2022-03-23 14:53

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20220323_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedlisthotels',
            name='hotels',
            field=sortedm2m.fields.SortedManyToManyField(default=None, help_text=None, to='api.Hotel'),
        ),
    ]
