# Generated by Django 3.2.5 on 2022-03-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_cachedlisthotels_hotels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CachedListHotels',
        ),
    ]
