# Generated by Django 3.2.5 on 2022-03-23 14:55

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_delete_cachedlisthotels'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedListHotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywordHash', models.CharField(default=None, max_length=32, null=True)),
                ('cached_on', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.city')),
                ('hotels', sortedm2m.fields.SortedManyToManyField(default=None, help_text=None, to='api.Hotel')),
            ],
            options={
                'unique_together': {('city', 'keywordHash')},
            },
        ),
    ]
